# Databricks Apps Configuration for Quill
# Production deployment configuration

name: quill
description: "Quill - Financial Services Intelligent Assistant"

# Application command
command: ['streamlit', 'run', 'app.py']

# Production environment variables
env:
  # Production Mode (CRITICAL)
  - name: 'APP_DEVELOPMENT_MODE'
    value: 'false'
  - name: 'APP_DEBUG'
    value: 'false'
  
  # Model Configuration
  - name: 'QUESTION_EXTRACTION_MODEL'
    value: 'databricks-claude-3-7-sonnet'
  - name: 'ANSWER_GENERATION_MODEL'
    value: 'agents_users-afsana_afzal-mbo_demo'
  
  # Storage and Warehouse
  - name: 'DATABRICKS_VOLUME_PATH'
    value: '/Volumes/main/default/aria'
  
  # Application Settings
  - name: 'APP_MAX_FILE_SIZE_MB'
    value: '50'
  - name: 'TRACKING_ENABLED'
    value: 'true'

# Resource requirements
resources:
  cpu: "1"
  memory: "2Gi"