"""Configuration module for ARIA application.

This module provides centralized configuration management with environment variable
loading, validation, and type safety.
"""

from .config import config, AppConfig, domain_config, settings

# Export all constants for backward compatibility
from .config import (
    SUPPORTED_FILE_TYPES, MAX_FILE_SIZE_MB, MAX_QUESTIONS_PER_BATCH,
    AVAILABLE_CLAUDE_MODELS, DEFAULT_QUESTION_EXTRACTION_MODEL,
    DEFAULT_TIMEOUT_SECONDS, MAX_RETRIES, RETRY_WAIT_SECONDS,
    SIDEBAR_WIDTH, PREVIEW_HEIGHT, GRID_HEIGHT,
    DEFAULT_MAX_TOKENS, DEFAULT_TEMPERATURE, BATCH_MAX_TOKENS,
    QUESTION_ID_PATTERN, FALLBACK_QUESTION_PATTERN,
    # Prompt constants are now defined at the top of config.py
    QUESTION_EXTRACTION_SYSTEM_PROMPT, ANSWER_GENERATION_SYSTEM_PROMPT, DEFAULT_CUSTOM_PROMPT,
    SESSION_KEYS, ERROR_MESSAGES, SUCCESS_MESSAGES,
    CSS_CLASSES, SUPPORTED_EXTENSIONS, EXPORT_EXTENSIONS,
    MIME_TYPES, COLUMN_MAPPINGS, AGGRID_CONFIG
)

__all__ = [
    "config", "AppConfig", "domain_config", "settings",
    "SUPPORTED_FILE_TYPES", "MAX_FILE_SIZE_MB", "MAX_QUESTIONS_PER_BATCH",
    "AVAILABLE_CLAUDE_MODELS", "DEFAULT_QUESTION_EXTRACTION_MODEL",
    "DEFAULT_TIMEOUT_SECONDS", "MAX_RETRIES", "RETRY_WAIT_SECONDS",
    "SIDEBAR_WIDTH", "PREVIEW_HEIGHT", "GRID_HEIGHT",
    "DEFAULT_MAX_TOKENS", "DEFAULT_TEMPERATURE", "BATCH_MAX_TOKENS",
    "QUESTION_ID_PATTERN", "FALLBACK_QUESTION_PATTERN",
    "QUESTION_EXTRACTION_SYSTEM_PROMPT", "ANSWER_GENERATION_SYSTEM_PROMPT", "DEFAULT_CUSTOM_PROMPT",
    "SESSION_KEYS", "ERROR_MESSAGES", "SUCCESS_MESSAGES",
    "CSS_CLASSES", "SUPPORTED_EXTENSIONS", "EXPORT_EXTENSIONS",
    "MIME_TYPES", "COLUMN_MAPPINGS", "AGGRID_CONFIG"
]
